import type { Metadata } from "next";
import { SITE_CONFIG } from "@/lib/constants";
import {
  BreadcrumbJsonLd,
  WebPageJsonLd,
  WebApplicationJsonLd,
  FAQJsonLd,
  HowToJsonLd,
} from "@/components/seo/json-ld";
import { InheritanceTaxCalculator } from "@/components/calculators/inheritance-tax-calculator";

export const metadata: Metadata = {
  title: "Inheritance Tax Calculator | Free Estate & Inheritance Tax Estimator (2026) | Measurely",
  description: "Free inheritance tax calculator. Estimate estate taxes, inheritance tax liability, net inheritance, and beneficiary shares. Supports US, UK, Canada, Australia, and NZ tax rules.",
  openGraph: {
    title: "Inheritance Tax Calculator | Free Estate Tax Estimator (2026)",
    description: "Free inheritance tax calculator supporting US, UK, Canada, Australia, and NZ tax rules. Estimate estate taxes, net inheritance, and beneficiary distributions.",
    url: `${SITE_CONFIG.url}/inheritance-tax-calculator`,
    siteName: SITE_CONFIG.siteName,
    type: "website",
    images: [{ url: `${SITE_CONFIG.url}${SITE_CONFIG.ogImage}`, width: 1200, height: 630, alt: "Inheritance Tax Calculator" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Inheritance Tax Calculator | Free Estate Tax Estimator (2026)",
    description: "Free inheritance tax calculator supporting US, UK, Canada, Australia, and NZ. Estimate estate taxes, net inheritance, and beneficiary shares.",
    images: [`${SITE_CONFIG.url}${SITE_CONFIG.ogImage}`],
  },
  alternates: { canonical: `${SITE_CONFIG.url}/inheritance-tax-calculator` },
  keywords: ["inheritance tax calculator", "estate tax calculator", "inheritance tax estimator", "inheritance tax by state", "estate planning calculator", "inheritance tax liability", "probate tax calculator", "inheritance value calculator"],
};

const faqs = [
  { question: "What is inheritance tax?", answer: "Inheritance tax is a tax paid by a person who inherits money or property from someone who has died. Unlike estate tax (which is paid by the estate), inheritance tax is paid by the beneficiary. Not all countries or states charge inheritance tax." },
  { question: "Is inheritance tax the same as estate tax?", answer: "No, they differ. Estate tax is levied on the total value of the deceased person's estate before distribution to beneficiaries. Inheritance tax is paid by the beneficiary on what they receive. The US has a federal estate tax but no federal inheritance tax." },
  { question: "Who is exempt from inheritance tax?", answer: "Spouses are typically exempt from inheritance tax in most jurisdictions. Other exemptions may include charities, minor children, and transfers below certain thresholds. Exemptions vary significantly by country and state." },
  { question: "How is inheritance tax calculated?", answer: "Inheritance tax is calculated by determining the estate value, subtracting allowable deductions and exemptions, applying the applicable tax rate, and dividing remaining tax among beneficiaries based on their inheritance shares." },
  { question: "Are inherited assets taxable?", answer: "Inherited assets are generally not subject to income tax. However, any income generated by inherited assets (such as interest, dividends, or rental income) is taxable. Capital gains tax may apply when you sell inherited assets." },
  { question: "Can gifts reduce inheritance tax?", answer: "Yes, making lifetime gifts can reduce inheritance tax liability in many jurisdictions. Gifts made more than 7 years before death often fall outside the estate for tax purposes. Annual gift allowances also apply in many countries." },
  { question: "Do all countries charge inheritance tax?", answer: "No. Many countries have abolished inheritance and estate taxes, including Australia, Canada, New Zealand, Sweden, and Russia. Others like the US and UK have significant exemptions before tax applies." },
  { question: "How accurate is this calculator?", answer: "This calculator provides estimates based on common tax rules for each jurisdiction. Actual tax liability depends on specific circumstances, state laws, and professional assessment. Use this as a planning tool and consult a tax professional." },
];

const howToSteps = [
  { name: "Select Your Country", text: "Choose the jurisdiction whose tax rules apply to the estate (US, UK, Canada, Australia, or New Zealand)." },
  { name: "Enter Estate Value", text: "Input the total gross value of the estate including property, investments, cash, and other assets." },
  { name: "Add Deductions", text: "Enter outstanding debts, funeral expenses, charitable donations, and other allowable deductions." },
  { name: "Set Beneficiary Details", text: "Indicate whether a spouse exemption applies and the number of beneficiaries." },
  { name: "Calculate", text: "Press the Calculate button to estimate inheritance tax, net inheritance, and beneficiary shares." },
];

export default function InheritanceTaxCalculatorPage() {
  return (
    <>
      <BreadcrumbJsonLd
        items={[
          { name: SITE_CONFIG.name, url: SITE_CONFIG.url },
          { name: "Finance Calculators", url: `${SITE_CONFIG.url}/finance` },
          { name: "Inheritance Tax Calculator", url: `${SITE_CONFIG.url}/inheritance-tax-calculator` },
        ]}
      />
      <WebPageJsonLd
        title="Inheritance Tax Calculator | Free Estate & Inheritance Tax Estimator (2026)"
        description="Free inheritance tax calculator. Estimate estate taxes, inheritance tax liability, net inheritance, and beneficiary shares with multi-country support."
        url={`${SITE_CONFIG.url}/inheritance-tax-calculator`}
      />
      <WebApplicationJsonLd
        name="Inheritance Tax Calculator"
        description="Free inheritance tax calculator supporting US, UK, Canada, Australia, and NZ tax rules with detailed estate breakdowns."
        url={`${SITE_CONFIG.url}/inheritance-tax-calculator`}
        category="Calculator"
      />
      <FAQJsonLd questions={faqs} url={`${SITE_CONFIG.url}/inheritance-tax-calculator`} />
      <HowToJsonLd
        name="How to Use the Inheritance Tax Calculator"
        description="Step-by-step guide for using the Inheritance Tax Calculator to estimate estate taxes and net inheritance."
        steps={howToSteps}
        url={`${SITE_CONFIG.url}/inheritance-tax-calculator`}
      />
      <InheritanceTaxCalculator />
    </>
  );
}
